--工作量占比
WITH A AS (
SELECT A.RWBH, A.RWMC, A.GZLB, A.ZYX, B.VAL LBVAL, C.VAL ZYXVAL, A.SC, A.SCXS, A.ZLQZ, A.FZR,
(B.VAL+C.VAL)*A.SC*A.SCXS*A.ZLQZ PJ1, RATIO_TO_REPORT((B.VAL+C.VAL)*A.SC*A.SCXS*A.ZLQZ) OVER() BFB1
FROM TMP_RW A, TMP_GZLB B, TMP_ZYX C
WHERE A.GZLB=B.GZLB AND A.ZYX=C.ZYX)
--SELECT B.XM, SUM(A.BFB1*B.BFB) GRJX1, LOG(SUM(A.BFB1*B.BFB),10)*SUM(A.BFB1*B.BFB) GRJX2
SELECT B.XM as "姓名", SUM(A.BFB1*B.BFB) as "原始占比", LOG(SUM(A.BFB1*B.BFB),10)*SUM(A.BFB1*B.BFB) as "占比(log10)"
FROM A, TMP_GRBFB B, TMP_GRINFO C
WHERE A.RWBH=B.RWBH AND B.XM=C.XM 
GROUP BY B.XM
ORDER BY 2 DESC 

--个人工作量占比
WITH A AS (
SELECT A.RWBH, A.RWMC, A.GZLB, A.ZYX, B.VAL LBVAL, C.VAL ZYXVAL, A.SC, A.SCXS, A.ZLQZ, A.FZR,
(B.VAL+C.VAL)*A.SC*A.SCXS*A.ZLQZ PJ1, RATIO_TO_REPORT((B.VAL+C.VAL)*A.SC*A.SCXS*A.ZLQZ) OVER() BFB1
FROM TMP_RW A, TMP_GZLB B, TMP_ZYX C
WHERE A.GZLB=B.GZLB AND A.ZYX=C.ZYX)
SELECT A.RWBH, A.RWMC, B.XM, A.BFB1*B.BFB, C.FWLB, C.JB, C.YJF
FROM A, TMP_GRBFB B, TMP_GRINFO C
WHERE A.RWBH=B.RWBH AND B.XM=C.XM AND B.XM='&1'
ORDER BY 4 DESC 

--项目工作量占比明细
WITH A AS (
SELECT A.RWBH, A.RWMC, A.GZLB, A.ZYX, B.VAL LBVAL, C.VAL ZYXVAL, A.SC, A.SCXS, A.ZLQZ, A.FZR,
(B.VAL+C.VAL)*A.SC*A.SCXS*A.ZLQZ PJ1, RATIO_TO_REPORT((B.VAL+C.VAL)*A.SC*A.SCXS*A.ZLQZ) OVER() BFB1
FROM TMP_RW A, TMP_GZLB B, TMP_ZYX C
WHERE A.GZLB=B.GZLB AND A.ZYX=C.ZYX)
SELECT A.RWBH, A.RWMC, B.XM, A.BFB1*B.BFB, C.FWLB, C.JB, C.YJF
FROM A, TMP_GRBFB B, TMP_GRINFO C
WHERE A.RWBH=B.RWBH AND B.XM=C.XM AND A.RWBH='&1'
ORDER BY 4 DESC 

