--IT部员工业绩分
WITH A AS (
SELECT A.RWBH, A.RWMC, A.GZLB, A.ZYX, B.VAL LBVAL, C.VAL ZYXVAL, A.SC, A.SCXS, A.ZLQZ, A.FZR,
(B.VAL+C.VAL)*A.SC*A.SCXS*A.ZLQZ PJ1, RATIO_TO_REPORT((B.VAL+C.VAL)*A.SC*A.SCXS*A.ZLQZ) OVER() BFB1
FROM TMP_RW A, TMP_GZLB B, TMP_ZYX C
WHERE A.GZLB=B.GZLB AND A.ZYX=C.ZYX)
SELECT B.XM, SUM(A.BFB1*B.BFB) GRJX1, LOG(SUM(A.BFB1*B.BFB),10)*SUM(A.BFB1*B.BFB) GRJX2, C.YJF, SUM(C.YJF) OVER() SUM_YJF, (RATIO_TO_REPORT(SUM(A.BFB1*B.BFB)) OVER ())*(SUM(C.YJF) OVER()) GRYJF, (RATIO_TO_REPORT(SUM(A.BFB1*B.BFB)) OVER ())*(SUM(C.YJF) OVER())-C.YJF GRYJF_DIFF
FROM A, TMP_GRBFB B, TMP_GRINFO C
WHERE A.RWBH=B.RWBH AND B.XM=C.XM AND C.FWLB='GS'
GROUP BY B.XM, C.YJF
ORDER BY 2 DESC 
